apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-world-tls
  namespace: default
  labels:
    owner: ingress
spec:
  secretName: hello-world-tls
  dnsNames:
    - hello-world-loicsteve.com
  issuerRef:
    name: cloudflare-issuer
    kind: Issuer
    group: cert-manager.io
